"""add admin_id to users and stations

Revision ID: ab17bdd80000
Revises: 8312b25bcb4f
Create Date: 2025-05-19 01:05:14.915634

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab17bdd80000'
down_revision: Union[str, None] = '8312b25bcb4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin_id', sa.String(), nullable=True))
    op.add_column('stations', sa.Column('admin_id', sa.String(), nullable=True))
    # После применения миграции заполните admin_id для всех станций вручную,
    # затем можно сделать отдельную миграцию для nullable=False
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stations', 'admin_id')
    op.drop_column('users', 'admin_id')
    # ### end Alembic commands ###
