"""make admin_id not null in stations

Revision ID: bfb9747f2241
Revises: ab17bdd80000
Create Date: 2025-05-19 01:08:41.487637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfb9747f2241'
down_revision: Union[str, None] = 'ab17bdd80000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('stations', 'admin_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
